### PR TITLE
added webpack

### PR DESCRIPTION
**Pull request by dariia-kachalova**
please review

### CODE REVIEW

**Comment by Tsarar** [comment]
Did you test the webpack build on some website? Is it working?

**Comment by dariia-kachalova** [comment]
When I run it on our project it writes that webpack compilled.
Generally it looks suspicious for me, as when I try to change command for npm watch, it throws an error.

**Review by dangoth — APPROVED** [review]
Approving as per confirmation in chat that the issues were local to Dariia's env

**Comment by dariia-kachalova** [comment]
Closing this request as webpack have been already added by Vladyslav

**Pull request closed without merging**
